services:
  # Main web service
  - type: web
    name: dbi
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - src/**
        - requirements.txt
        - Dockerfile
